### ISSUE TITLE
Current user is anonymous when injecting CustomerFacade f.e. in a class that implements ApplicationListener

### ISSUE THREAD

**Issue by vasilb751** [nemesis-software/nemesis-support#12]
I work on a feature that a client opens a websocket, subscribe to a topic and display incoming messages. 

Here is my class:

````
public class SessionSubscribeEventApplicationListener implements ApplicationListener<org.springframework.web.socket.messaging.SessionSubscribeEvent> {

   @Resource(name = CustomerFacade.NAME)
    private CustomerFacade customerFacade;

    @Override
    public void onApplicationEvent(SessionSubscribeEvent event) {
          String currentUser = customerFacade.getCurrentCustomer().getUsername();
    }
}
````

I expected that `currentUser` will return the user that opened websocket, but  actually it returns anonymous user.

This is strange for me, because I can get currrent user from 'event' parameter using `event.getUser().getName()`

**Comment by gochev** [comment]
Yeah the issue is happening probably because in order customerFacade to work we need a http request that is started from a user.

When you are in an application listener it is executed in a different thread and yeah.. no user, since no request, no id in the session and so on... maybe we should somehow stop developers of using currentXXXX methods which are on thread level outside of the http request thread ?

**Comment by ptahchiev** [comment]
Hi Vasil,

please format your issue. If you're not sure how to do that, please read the following:

 - https://guides.github.com/features/issues/
 - https://help.github.com/categories/writing-on-github/

Also, please specify which version of the nemesis platform you use. Also I don't know what `ApplicatioonEvent` you are trying to intercept. Is this the `SessionCreatedEvent` - in that case you are still not logged-in (this event is raised when you are still anonymous, before the actual login).

**Comment by vasilb751** [comment]
The problem was  in  my tv :)

After detailed reading page https://docs.spring.io/spring-security/site/docs/current/reference/html/websocket.html

I missed 23.1
