### ISSUE TITLE
EntityService to expose EntityManager's getReference

### ISSUE THREAD

**Issue by binis2** [nemesis-software/nemesis-support#23]
It would be helpful addition to nemesis' EntityService to expose EntityManager::getReference method.

Optional but less preferable solution will be to expose EntityServiceImp::getEntityManager() into the interface. The problem with that approach is that you have to use the actual implementation of certain entity instead of the definition. 

This method is helpful when you want to persist an entity and don't want to pull dependent/child entities from the database when you know their ids.

**Comment by ptahchiev** [comment]
This issue is fixed in 1.5.3
