### ISSUE TITLE
Generate abstract entity

### ISSUE THREAD

**Issue by slavypopov** [nemesis-software/nemesis-support#3]
Hi, 

Currently I have an entity that is called Abstract...Entity, but it is not really abstract. This entity is supposed to be the root of inheritance tree (in my case single table inheritance strategy). It will be nice to have an annotation e.g. `@AbstractDefinition` that will lead to generation of abstract class. 
if you need more info plase contact me in skype: slavy_popov
Best regards,
Slavy

**Comment by ptahchiev** [comment]
Hello Slavy,
thank you for your suggestion. We also have the same cases with `AbstractOrderEntity` which is the root of inheritance for both `CartEntityDefinition ` and `OrderEntityDefinition` so it is a good enhancement proposal. We will take it into consideration.
