### ISSUE TITLE
isPlatformInitializing issue

### ISSUE THREAD

**Issue by gochev** [nemesis-software/nemesis-support#4]
Currently we have an issue with the IsPlatformInitializing when RedisApplicationScopeStrategyImpl is used with external redis. In short it looks the initialize value stays false after the app is initialized.

Version 1.5.0

How to reproduce
1) start external redis.
2) run init-db
3) spring-boot:run
4) you will notice maintanance page is shown.

The problem is that the redis has never been shut down and it looks even if we set the value for  PlatformServiceImpl.NEMESIS_PLATFORM_INITIALIZING to false after initializeDatabase for some reason it is not updated.

**Comment by ptahchiev** [comment]
Hello Nayden,

Can you please confirm this issue is still relevant in 1.5.1?

**Comment by gochev** [comment]
I believe it is fixed.
